---
- name: install dum0 network interface
  template:
    src: "dum0.conf.j2"
    dest: "/etc/network/interfaces.d/dum0.conf"
    owner: root
    group: root
    mode: 0644
  when: consul_use_systemd
  notify:
    - reload systemd

- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
  when: consul_use_systemd

